### ISSUE TITLE
Blockquoeto (Her neyse : ) )

### ISSUE THREAD

**Issue by neynefes** [ubuntu-tr/ubuntu-tr.github.io#41]
Bunun sol kısmında renklendirme yapmıştım. Önemli notlarda sol border kısmının rengi kırmızı olabilir mi? Hatta içine ünlem işareti bile konulması sağlanabilir.

**Comment by bugra9** [comment]
Önemli olduğunu nasıl anlayacağız?

**Comment by neynefes** [comment]
Biz yazacağız. Öyle bir kullanım olur mu? css'ye eklenebilir mi?

**Comment by bugra9** [comment]
Tamam bunu da ekleyeyim.

**Comment by betseg** [comment]
``` css
.markdown-body blockquote.önemli {
  border-left: 4px solid #F44336;
}
```
