### ISSUE TITLE
Code bloğunun sağ üstüne icon

### ISSUE THREAD

**Issue by neynefes** [ubuntu-tr/ubuntu-tr.github.io#46]
http://bloginn-jekyll.justgoodthemes.com/style-guide/
Bu sitedeki gibi code etiketlerinin sağ üstüne simge koyabilir misiniz?

Python vs için ayrı adlandırma tadından yenmez tabi :D

**Comment by betseg** [comment]
``` css
.code neyse.ondan:before {
    content: '(buraya font-awesome kod ikonu gelecek)';
    font-family: FontAwesome;
    top:0;right:0;display:block;color:darkgray;background:lightgray;
    position:falan filan;
}
```

Oldu mu :D
